name = "dejavu-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "dejavu-api.enio.la", custom_domain = true }
]

[durable_objects]
bindings = [{ name = "GAME_ROOM", class_name = "GameRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "dejavu_analytics"

[vars]
CALLS_APP_ID = ""
